name: Publish

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/python-publish.yml"
      - "pyproject.toml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
